### PR TITLE
upgrade kyma_version to 1.23.1

### PR DESCRIPTION
**Pull request by lauraanddola**
try to implement [Upgrade Kyma on KCP to 1.23.1 -> 1.24.0](https://github.tools.sap/kyma/backlog/issues/1653)

### CODE REVIEW

**Comment by lauraanddola** [comment]
test all

**Comment by lauraanddola** [comment]
test pre-main-control-plane-gke-integration

**Comment by lauraanddola** [comment]
retest pre-main-control-plane-gke-integration

**Review by piotrmiskiewicz — APPROVED** [review]

**Pull request merged**
