### PR TITLE
KEB jobs Dockerfile cleanup

### PR DESCRIPTION
**Pull request by wozniakjan**
**Description**

There is a newly introduced generic Dockerfile for KEB jobs - https://github.com/kyma-project/control-plane/pull/2475. This PR depends on https://github.com/kyma-project/test-infra/pull/6929 and removes no longer necessary `Dockerfiles`.

### CODE REVIEW

**Comment by wozniakjan** [comment]
https://github.com/kyma-project/test-infra/pull/6929 merged, opening for reviews

**Comment by wozniakjan** [comment]
https://github.com/kyma-project/test-infra/pull/7023#discussion_r1118393206
recent development in `image-builder` likely causing job builds to fail

**Review by ralikio — APPROVED** [review]

**Pull request merged**
