### PR TITLE
Rebuild all components

### PR DESCRIPTION
**Pull request by pkosiec**
**Description**

Changes proposed in this pull request:

- Rebuild all components

### CODE REVIEW

**Comment by franpog859** [comment]
@pkosiec , I cannot see the `pre-control-plane-components-provisioner` job here 😨 Do you know maybe, what could have happened? It causes the integration jobs to fail and there will be no new images of the component 😢

**Comment by pkosiec** [comment]
Yeah @franpog859, we're investigating that... something is wrong after our cleanup 😞

**Comment by pkosiec** [comment]
Merging with admin rights, as it blocks all KCP contributors. The PR basically doesn't change anything apart from PR images.

**Pull request merged**
