### PR TITLE
Create operators ClusterRoleBindings before Kyma installation

### PR DESCRIPTION
**Pull request by franpog859**
**Description**

Changes proposed in this pull request:

- Create operators ClusterRoleBindings before Kyma installation

**Related issue(s)**

See [the issue #249](https://github.com/kyma-project/control-plane/issues/249)

ClusterRoleBindings created on SKR before Kyma installation:

````
k get clusterrolebinding l2-operator-view -oyaml                                                                                                                                                                                          
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: "2020-11-16T10:58:52Z"
  labels:
    app: kyma
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
      f:roleRef:
        f:apiGroup: {}
        f:kind: {}
        f:name: {}
      f:subjects: {}
    manager: main
    operation: Update
    time: "2020-11-16T10:58:52Z"
  name: l2-operator-view
  resourceVersion: "2153"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterrolebindings/l2-operator-view
  uid: 1c8aa684-fe68-41c4-b8e2-7a3c2de73a20
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: runtimeOperator

k get clusterrolebinding l3-operator-admin -oyaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: "2020-11-16T10:58:52Z"
  labels:
    app: kyma
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
      f:roleRef:
        f:apiGroup: {}
        f:kind: {}
        f:name: {}
      f:subjects: {}
    manager: main
    operation: Update
    time: "2020-11-16T10:58:52Z"
  name: l3-operator-admin
  resourceVersion: "2154"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterrolebindings/l3-operator-admin
  uid: de413dce-944c-4593-a245-6ba9891a0604
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: runtimeAdmin


````

### CODE REVIEW

**Review by ebensom — APPROVED** [review]
LGTM from role/binding correctness point of view.

**Review by Maladie — APPROVED** [review]
Seems legit

**Pull request merged**
