### PR TITLE
set EnableNatGateway boolean to true for Azure, AzureLite and AzureHA for upgrades

### PR DESCRIPTION
**Pull request by tillknuesting**
As part of enabling NAT Gateway for Azure clusters, this PR sets the EnableNatGateway boolean to true for Azure, AzureLite, and AzureHA plans.

See for more information: https://github.com/kyma-project/kyma/issues/13553

When a partial payload is provided, Provisioner gets the missing information from the database with previously used data, and therefore only values that are different are changed and only providing EnableNatGateway should be sufficient.

### CODE REVIEW

**Review by ebensom — COMMENTED** [review]
We MUST NOT reconfigure existing cluster to use NAT gateway as it would involve change of the outbound IPs used for the exiting runtimes. Who requested this change?

**Comment by tillknuesting** [comment]
> We MUST NOT reconfigure existing cluster to use NAT gateway as it would involve change of the outbound IPs used for the exiting runtimes. Who requested this change?

https://github.com/kyma-project/kyma/issues/13553#issuecomment-1167053459

**Pull request closed without merging**
