### PR TITLE
Adjust azure_lite autoScalerMax settings

### PR DESCRIPTION
**Pull request by voigt**
**Description**

Changes proposed in this pull request:

- Adjust autoScalerMax for create and update on azure_lite plan to:
```
 "properties": {
                    "autoScalerMax": {
                      "default": 10,
                      "description": "Specifies the maximum number of virtual machines to create",
                      "maximum": 40,
                      "minimum": 2,
                      "type": "integer"
                    }
```

**Related issue(s)**

- #1072

### CODE REVIEW

**Review by wozniakjan — DISMISSED** [review]
/lgtm
/hold

feel free to unhold after a successful test

**Comment by voigt** [comment]
Testing with the following config:

```json
{
	"service_id":"47c9dcbf-ff30-448e-ab36-d3bad66ba281",
	"plan_id":"8cb22518-aa26-44c5-91a0-e669ec9bf443",
	"context":{
		"globalaccount_id":"e449f875-b5b2-4485-b7c0-98725c0571bf",
		"subaccount_id":"94b39299-ea12-4cf7-9abd-9caabbf3dad9",
		"user_id":"christoph.voigt@sap.com"
	},
	"parameters":{
		"name":"cvoigt-deleteme1",
		"autoScalerMin": 2,
		"autoScalerMax": 50
	}
}
```

Returns `400 Bad Request`

```json
{
  "description": "while validating input parameters: autoScalerMax: Must be less than or equal to 40"
}
```

**Comment by voigt** [comment]
Creating SKR with following payload:

```json
{
	"service_id":"47c9dcbf-ff30-448e-ab36-d3bad66ba281",
	"plan_id":"8cb22518-aa26-44c5-91a0-e669ec9bf443",
	"context":{
		"globalaccount_id":"e449f875-b5b2-4485-b7c0-98725c0571bf",
		"subaccount_id":"94b39299-ea12-4cf7-9abd-9caabbf3dad9",
		"user_id":"christoph.voigt@sap.com"
	},
	"parameters":{
		"name":"cvoigt-deleteme1"
	}
}
```

```json
{
  "dashboard_url": "https://console.e3a4a37.kyma-dev.shoot.canary.k8s-hana.ondemand.com",
  "operation": "3e73bce1-330f-4252-aa2f-fcd4957c1c4e",
  "metadata": {
    "labels": {
      "KubeconfigURL": "https://kyma-env-broker.cp.dev.kyma.cloud.sap/kubeconfig/803d5362-8356-4690-a09f-2abc52e0542d",
      "Name": "cvoigt-deleteme1"
    }
  }
}
```

Creates a shoot like this:

image

**Review by piotrmiskiewicz — APPROVED** [review]

**Review by wozniakjan — APPROVED** [review]

**Review by NHingerl — APPROVED** [review]

**Pull request merged**
