### PR TITLE
Add New Machine Type for Azure

### PR DESCRIPTION
**Pull request by ukff**
Changes proposed in this pull request:
- Extend available machine type list in KEB to cover those supported by kyma-metrics-colector

### CODE REVIEW

**Review by ebensom — COMMENTED** [review]
Make sure to update the image version in the chart:
https://github.com/kyma-project/control-plane/blob/main/resources/kcp/charts/kyma-environment-broker/values.yaml#L5

**Review by szwedm — APPROVED** [review]
/lgtm

**Pull request merged**
