### PR TITLE
Do not Log kubeconfig hash

### PR DESCRIPTION
**Pull request by jaroslaw-pieszka**
**Description**

Currently hash is logged as binary converted to string.

Changes proposed in this pull request:

- `kubeconfig` hash is not logged any more

**Related issue(s)**

### CODE REVIEW

**Review by wozniakjan — DISMISSED** [review]
/lgtm
/approve

**Review by wozniakjan — DISMISSED** [review]

**Review by wozniakjan — DISMISSED** [review]

**Review by ralikio — CHANGES_REQUESTED** [review]
Do we need to log that hash of Kubeconfig? It seems to be kind of a secret for me. Can we remove that line completely?

**Comment by jaroslaw-pieszka** [comment]
> Do we need to log that hash of Kubeconfig? It seems to be kind of a secret for me. Can we remove that line completely?

It is secret hence we log hash of it. To detect differences but to conceal the secret itself.

**Comment by jaroslaw-pieszka** [comment]
@TorstenD-SAP suggested not to log `kubeconfig` hash since `kubeconfig` may contain static tokens and logging hash make brute force attack possible .

**Review by tillknuesting — APPROVED** [review]

**Pull request merged**
