### PR TITLE
All necessary fields moved from XXXOperation to Operation type

### PR DESCRIPTION
**Pull request by piotrmiskiewicz**
**Description**

Changes proposed in this pull request:
- all type of operation specific data bounded together in the Operation. This is one of a step, which allows a refactoring and get rid of specific types of operations.
- methods like toProvisioningOperation in the storage was modified to unmarshall data after calling toOperation.

**Related issue(s)**

### CODE REVIEW

**Comment by szwedm** [comment]
please bump KEB img in values.yaml

**Comment by ralikio** [comment]
Please correct issue from: https://github.com/kyma-project/control-plane/pull/1872/files/d93a705f135824051883de6209e857a5be7eedeb#r925382727

**Pull request merged**
