### PR TITLE
Adding MachineType update test

### PR DESCRIPTION
**Pull request by wozniakjan**
**Description**

followup to https://github.com/kyma-project/control-plane/pull/2447 with simple test for machine type update.

see also: https://github.com/kyma-project/control-plane/issues/2497

### CODE REVIEW

**Comment by wozniakjan** [comment]
/hold
test seems flaky for some reason

**Comment by wozniakjan** [comment]
/unhold
flakiness resolved https://github.com/kyma-project/control-plane/pull/2509/commits/402e738e0df5057dbd1196178dda51f8515e0f8d

**Review by szwedm — APPROVED** [review]
/lgtm

**Pull request merged**
