### PR TITLE
Update reconciler images

### PR DESCRIPTION
**Pull request by marcobebway**
**Description**

Update reconciler images for https://github.com/kyma-incubator/reconciler/pull/594.

### CODE REVIEW

**Review by tobiscr — APPROVED** [review]

**Review by pxsalehi — APPROVED** [review]

**Review by VladislavPaskar — DISMISSED** [review]

**Comment by marcobebway** [comment]
Verified here: https://github.com/kyma-project/test-infra/pull/4588.

**Review by pxsalehi — APPROVED** [review]

**Pull request merged**
