### PR TITLE
Update kubernetes dependencies

### PR DESCRIPTION
**Pull request by nachtmaar**
**Description**

Changes proposed in this pull request:

- Upgrade kubernetes dependencies to v1.20.11 because
- The large block of replacements for kubernetes dependencies is due to the fact that [kubernetes sets some requirements to version v0.0.0](https://github.com/kubernetes/kubernetes/blob/v1.21.5/go.mod#L112)

### CODE REVIEW

**Review by FriedrichWilken — CHANGES_REQUESTED** [review]
@nachtmaar please bump the image. :)

**Review by FriedrichWilken — APPROVED** [review]

**Comment by FriedrichWilken** [comment]
Looks like I am not code owner of all three files.

**Review by marcobebway — APPROVED** [review]
/lgtm

**Review by marcobebway — APPROVED** [review]
/approve

**Pull request merged**
