### PR TITLE
Adjust KCP to Kyma 1.18

### PR DESCRIPTION
**Pull request by jasiu001**
**Description**
Adjust KCP to Kyma 1.18

Changes proposed in this pull request:

- remove `istio-kyma-patch` component
- remove `installer-local.yaml` file, replacing it with a file `installer.yaml`
- fix deprecated resources in `installer.yaml`
- remove unused rule `ci-create-release-artifacts` from Makefile
- remove testdefinitions `logging` from `pre-master-control-plane-integration` prow job due to error occur on minikube

### CODE REVIEW

**Comment by ebensom** [comment]
I'd say let's add the profile: production into the Installer spec of Kyma

**Comment by jasiu001** [comment]
https://github.tools.sap/kyma/backlog/issues/1213

**Review by polskikiel — APPROVED** [review]

**Review by franpog859 — APPROVED** [review]
LGTM

**Pull request merged**
