### PR TITLE
Provisioner data model change: cluster name is no longer unique

### PR DESCRIPTION
**Pull request by akgalwas**
**Description**

Changes proposed in this pull request:

- Unique constraint removed from gardener_config.name field

### CODE REVIEW

**Review by koala7659 — APPROVED** [review]
LGTM

**Review by koala7659 — CHANGES_REQUESTED** [review]
I think you forgot to also update main sql schema file components/provisioner/assets/database/provisioner.sql

**Review by piotrmiskiewicz — APPROVED** [review]

**Review by koala7659 — APPROVED** [review]

**Pull request merged**
