### PR TITLE
Gardener version bumped to v1.65.2

### PR DESCRIPTION
**Pull request by akgalwas**
**Description**

Changes proposed in this pull request:

- Gardener updated to version 1.66.0 

**Related issue(s)**
https://github.com/kyma-project/control-plane/issues/2593

### CODE REVIEW

**Review by koala7659 — APPROVED** [review]
LGTM

**Review by koala7659 — CHANGES_REQUESTED** [review]
Please update values.yaml file to align provisioner image with PR

**Review by koala7659 — APPROVED** [review]
LGTM

**Review by ebensom — APPROVED** [review]

**Pull request merged**
