### PR TITLE
bump docker build image to go 1.18.1 in KMC

### PR DESCRIPTION
**Pull request by FriedrichWilken**
This PR updates the Dockerfile to use `golang:1.18.1-alpine3.15` for building the actual KMC image. This prevents possible security vulnerabilities in golang before version `1.18.1`.

### CODE REVIEW

**Comment by FriedrichWilken** [comment]
/pre-main-control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener

**Comment by nachtmaar** [comment]
@FriedrichWilken You need to bump the image to `eu.gcr.io/kyma-project/control-plane/kyma-metrics-collector:PR-1590`
/hold
Can you make the PR description a bit more descriptive ? :)

**Comment by FriedrichWilken** [comment]
I am closing this in favour of https://github.com/kyma-project/control-plane/pull/1593

**Pull request closed without merging**
