### PR TITLE
Do not use the deprecated confirmation annotation

### PR DESCRIPTION
**Pull request by ialidzhikov**
**Description**

`confirmation.garden.sapcloud.io` is deprecated with https://github.com/gardener/gardener/pull/1833 and will be removed in a future release of gardener/gardener.

### CODE REVIEW

**Comment by ebensom** [comment]
@Disper Can you please pass this to frogs for review? Thanks much!

**Comment by Disper** [comment]
@ebensom Done!
For the future reviews you can also ping all of us using the @kyma-project/framefrog team mention :).

**Review by akgalwas — APPROVED** [review]

**Pull request merged**
