### PR TITLE
Provisioner - Adding a feature flag to dump generated Gardener shoot spec into logs

### PR DESCRIPTION
**Pull request by koala7659**
Experimental feature to test KIM

For more info see https://github.com/kyma-project/infrastructure-manager/issues/185

### CODE REVIEW

**Comment by koala7659** [comment]
Environement: DEV
Plan: Azure


```
metadata:
  annotations:
    compass.provisioner.kyma-project.io/operation-id: bd4c0281-f43d-47d4-9887-6fe96ed0c2e4
    compass.provisioner.kyma-project.io/runtime-id: 43f0b98c-9851-484b-be1b-cda9e953de16
    kcp.provisioner.kyma-project.io/operation-id: bd4c0281-f43d-47d4-9887-6fe96ed0c2e4
    kcp.provisioner.kyma-project.io/runtime-id: 43f0b98c-9851-484b-be1b-cda9e953de16
  creationTimestamp: null
  labels:
    account: 461f6292-8085-41c8-af0c-e185f39b5e18
    subaccount: pg-test-su3
  name: c-361112f
  namespace: garden-kyma-dev
spec:
  cloudProfileName: az
  dns:
    domain: c-361112f.dev.kyma.ondemand.com
    providers:
    - domains:
        include:
        - c-361112f.dev.kyma.ondemand.com
      primary: true
      secretName: aws-route53-secret-dev
      type: aws-route53
  extensions:
  - providerConfig:
      apiVersion: service.dns.extensions.gardener.cloud/v1alpha1
      dnsProviderReplication:
        enabled: true
      kind: DNSConfig
    type: shoot-dns-service
  - providerConfig:
      apiVersion: service.cert.extensions.gardener.cloud/v1alpha1
      kind: CertConfig
      shootIssuers:
        enabled: true
    type: shoot-cert-service
  - disabled: false
    type: shoot-networking-filter
  kubernetes:
    enableStaticTokenKubeconfig: false
    kubeAPIServer:
      auditConfig:
        auditPolicy:
          configMapRef:
            name: audit-policy
      oidcConfig:
        clientID: 9bd05ed7-a930-44e6-8c79-e6defeb7dec9
        groupsClaim: groups
        issuerURL: https://kymatest.accounts400.ondemand.com
        signingAlgs:
        - RS256
        usernameClaim: sub
        usernamePrefix: '-'
    version: "1.27"
  maintenance:
    autoUpdate:
      kubernetesVersion: true
      machineImageVersion: false
  networking:
    nodes: 10.250.0.0/22
    type: calico
  provider:
    controlPlaneConfig:
      apiVersion: azure.provider.extensions.gardener.cloud/v1alpha1
      kind: ControlPlaneConfig
    infrastructureConfig:
      apiVersion: azure.provider.extensions.gardener.cloud/v1alpha1
      kind: InfrastructureConfig
      networks:
        vnet:
          cidr: 10.250.0.0/22
        zones:
        - cidr: 10.250.0.0/25
          name: 2
          natGateway:
            enabled: true
            idleConnectionTimeoutMinutes: 4
        - cidr: 10.250.0.128/25
          name: 1
          natGateway:
            enabled: true
            idleConnectionTimeoutMinutes: 4
        - cidr: 10.250.1.0/25
          name: 3
          natGateway:
            enabled: true
            idleConnectionTimeoutMinutes: 4
      zoned: true
    type: azure
    workers:
    - machine:
        image:
          name: gardenlinux
          version: 1312.3.0
        type: Standard_D2s_v5
      maxSurge: 3
      maxUnavailable: 0
      maximum: 20
      minimum: 3
      name: cpu-worker-0
      volume:
        size: 50Gi
        type: Standard_LRS
      zones:
      - "2"
      - "1"
      - "3"
  purpose: development
  region: westeurope
  secretBindingName: sap-skr-dev-cust-00002-kyma-integration
status:
  gardener:
    id: ""
    name: ""
    version: ""
  hibernated: false
  technicalID: ""
  uid: ""

```

**Comment by koala7659** [comment]
Env: Dev
PlanID: 361c511f-f939-4621-b228-d0fb79a1fe15 - AWS


```
metadata:
  annotations:
    compass.provisioner.kyma-project.io/operation-id: 81808d46-79c0-455a-9dba-6931ca927ff4
    compass.provisioner.kyma-project.io/runtime-id: aaee97e9-545a-4d3a-b90f-96a628fef328
    kcp.provisioner.kyma-project.io/operation-id: 81808d46-79c0-455a-9dba-6931ca927ff4
    kcp.provisioner.kyma-project.io/runtime-id: aaee97e9-545a-4d3a-b90f-96a628fef328
  creationTimestamp: null
  labels:
    account: 461f6292-8085-41c8-af0c-e185f39b5e18
    subaccount: pg-test-kyma2-su
  name: c-31ddf6f
  namespace: garden-kyma-dev
spec:
  cloudProfileName: aws
  dns:
    domain: c-31ddf6f.dev.kyma.ondemand.com
    providers:
    - domains:
        include:
        - c-31ddf6f.dev.kyma.ondemand.com
      primary: true
      secretName: aws-route53-secret-dev
      type: aws-route53
  extensions:
  - providerConfig:
      apiVersion: service.dns.extensions.gardener.cloud/v1alpha1
      dnsProviderReplication:
        enabled: true
      kind: DNSConfig
    type: shoot-dns-service
  - providerConfig:
      apiVersion: service.cert.extensions.gardener.cloud/v1alpha1
      kind: CertConfig
      shootIssuers:
        enabled: true
    type: shoot-cert-service
  - disabled: false
    type: shoot-networking-filter
  kubernetes:
    enableStaticTokenKubeconfig: false
    kubeAPIServer:
      auditConfig:
        auditPolicy:
          configMapRef:
            name: audit-policy
      oidcConfig:
        clientID: 9bd05ed7-a930-44e6-8c79-e6defeb7dec9
        groupsClaim: groups
        issuerURL: https://kymatest.accounts400.ondemand.com
        signingAlgs:
        - RS256
        usernameClaim: sub
        usernamePrefix: '-'
    version: "1.27"
  maintenance:
    autoUpdate:
      kubernetesVersion: true
      machineImageVersion: false
  networking:
    nodes: 10.250.0.0/22
    type: calico
  provider:
    controlPlaneConfig:
      apiVersion: aws.provider.extensions.gardener.cloud/v1alpha1
      kind: ControlPlaneConfig
    infrastructureConfig:
      apiVersion: aws.provider.extensions.gardener.cloud/v1alpha1
      kind: InfrastructureConfig
      networks:
        vpc:
          cidr: 10.250.0.0/22
        zones:
        - internal: 10.250.0.192/26
          name: eu-west-2c
          public: 10.250.0.128/26
          workers: 10.250.0.0/25
        - internal: 10.250.1.192/26
          name: eu-west-2b
          public: 10.250.1.128/26
          workers: 10.250.1.0/25
        - internal: 10.250.2.192/26
          name: eu-west-2a
          public: 10.250.2.128/26
          workers: 10.250.2.0/25
    type: aws
    workers:
    - machine:
        image:
          name: gardenlinux
          version: 1312.3.0
        type: m6i.large
      maxSurge: 3
      maxUnavailable: 0
      maximum: 20
      minimum: 3
      name: cpu-worker-0
      volume:
        size: 50Gi
        type: gp2
      zones:
      - eu-west-2c
      - eu-west-2b
      - eu-west-2a
  purpose: development
  region: eu-west-2
  secretBindingName: sap-aws-skr-dev-cust-00002-kyma-integration
status:
  gardener:
    id: ""
    name: ""
    version: ""
  hibernated: false
  technicalID: ""
  uid: ""
```

**Comment by koala7659** [comment]
Env: Dev
Plan: ca6e5357-707f-4565-bbbd-b3ab732597c6 GCP


```
metadata:
  annotations:
    compass.provisioner.kyma-project.io/operation-id: d173985d-c437-4677-a51b-c30c94ac256e
    compass.provisioner.kyma-project.io/runtime-id: 377c30d5-92bd-4025-97b7-0acffb6d8889
    kcp.provisioner.kyma-project.io/operation-id: d173985d-c437-4677-a51b-c30c94ac256e
    kcp.provisioner.kyma-project.io/runtime-id: 377c30d5-92bd-4025-97b7-0acffb6d8889
  creationTimestamp: null
  labels:
    account: 3e64ebae-38b5-46a0-b1ed-9ccee153a0ae
    subaccount: 39ba9a66-2c1a-4fe4-a28e-6e5db434084e
  name: a53a6b8
  namespace: garden-kyma-dev
spec:
  cloudProfileName: gcp
  dns:
    domain: a53a6b8.dev.kyma.ondemand.com
    providers:
    - domains:
        include:
        - a53a6b8.dev.kyma.ondemand.com
      primary: true
      secretName: aws-route53-secret-dev
      type: aws-route53
  extensions:
  - providerConfig:
      apiVersion: service.dns.extensions.gardener.cloud/v1alpha1
      dnsProviderReplication:
        enabled: true
      kind: DNSConfig
    type: shoot-dns-service
  - providerConfig:
      apiVersion: service.cert.extensions.gardener.cloud/v1alpha1
      kind: CertConfig
      shootIssuers:
        enabled: true
    type: shoot-cert-service
  - disabled: false
    type: shoot-networking-filter
  kubernetes:
    enableStaticTokenKubeconfig: false
    kubeAPIServer:
      auditConfig:
        auditPolicy:
          configMapRef:
            name: audit-policy
      oidcConfig:
        clientID: 9bd05ed7-a930-44e6-8c79-e6defeb7dec9
        groupsClaim: groups
        issuerURL: https://kymatest.accounts400.ondemand.com
        signingAlgs:
        - RS256
        usernameClaim: sub
        usernamePrefix: '-'
    version: "1.27"
  maintenance:
    autoUpdate:
      kubernetesVersion: true
      machineImageVersion: false
  networking:
    nodes: 10.250.0.0/22
    type: calico
  provider:
    controlPlaneConfig:
      apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
      kind: ControlPlaneConfig
      zone: europe-west3-c
    infrastructureConfig:
      apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
      kind: InfrastructureConfig
      networks:
        worker: 10.250.0.0/22
        workers: 10.250.0.0/22
    type: gcp
    workers:
    - machine:
        image:
          name: gardenlinux
          version: 1312.3.0
        type: n2-standard-2
      maxSurge: 3
      maxUnavailable: 0
      maximum: 20
      minimum: 3
      name: cpu-worker-0
      volume:
        size: 50Gi
        type: pd-standard
      zones:
      - europe-west3-c
      - europe-west3-b
      - europe-west3-a
  purpose: development
  region: europe-west3
  secretBindingName: gcp-skr-dev-cust-00002-kyma-integration
status:
  gardener:
    id: ""
    name: ""
    version: ""
  hibernated: false
  technicalID: ""
  uid: ""

```

**Comment by koala7659** [comment]
Env: Dev
PlanID: 8cb22518-aa26-44c5-91a0-e669ec9bf443 AzureLite

```
metadata:
  annotations:
    compass.provisioner.kyma-project.io/operation-id: 99be3000-407e-454f-b2ee-1647fbfd51af
    compass.provisioner.kyma-project.io/runtime-id: 8bc30e8b-7798-49d2-bed1-15cfa92bfe30
    kcp.provisioner.kyma-project.io/licence-type: TestDevelopmentAndDemo
    kcp.provisioner.kyma-project.io/operation-id: 99be3000-407e-454f-b2ee-1647fbfd51af
    kcp.provisioner.kyma-project.io/runtime-id: 8bc30e8b-7798-49d2-bed1-15cfa92bfe30
  creationTimestamp: null
  labels:
    account: 461f6292-8085-41c8-af0c-e185f39b5e18
    subaccount: pg-test-su3
  name: c-5b21cf0
  namespace: garden-kyma-dev
spec:
  cloudProfileName: az
  dns:
    domain: c-5b21cf0.dev.kyma.ondemand.com
    providers:
    - domains:
        include:
        - c-5b21cf0.dev.kyma.ondemand.com
      primary: true
      secretName: aws-route53-secret-dev
      type: aws-route53
  extensions:
  - providerConfig:
      apiVersion: service.dns.extensions.gardener.cloud/v1alpha1
      dnsProviderReplication:
        enabled: true
      kind: DNSConfig
    type: shoot-dns-service
  - providerConfig:
      apiVersion: service.cert.extensions.gardener.cloud/v1alpha1
      kind: CertConfig
      shootIssuers:
        enabled: true
    type: shoot-cert-service
  - disabled: false
    type: shoot-networking-filter
  kubernetes:
    enableStaticTokenKubeconfig: false
    kubeAPIServer:
      auditConfig:
        auditPolicy:
          configMapRef:
            name: audit-policy
      oidcConfig:
        clientID: 9bd05ed7-a930-44e6-8c79-e6defeb7dec9
        groupsClaim: groups
        issuerURL: https://kymatest.accounts400.ondemand.com
        signingAlgs:
        - RS256
        usernameClaim: sub
        usernamePrefix: '-'
    version: "1.27"
  maintenance:
    autoUpdate:
      kubernetesVersion: true
      machineImageVersion: false
  networking:
    nodes: 10.250.0.0/22
    type: calico
  provider:
    controlPlaneConfig:
      apiVersion: azure.provider.extensions.gardener.cloud/v1alpha1
      kind: ControlPlaneConfig
    infrastructureConfig:
      apiVersion: azure.provider.extensions.gardener.cloud/v1alpha1
      kind: InfrastructureConfig
      networks:
        vnet:
          cidr: 10.250.0.0/22
        zones:
        - cidr: 10.250.0.0/22
          name: 1
          natGateway:
            enabled: true
            idleConnectionTimeoutMinutes: 4
      zoned: true
    type: azure
    workers:
    - machine:
        image:
          name: gardenlinux
          version: 1312.3.0
        type: Standard_D4s_v5
      maxSurge: 1
      maxUnavailable: 0
      maximum: 10
      minimum: 2
      name: cpu-worker-0
      volume:
        size: 50Gi
        type: Standard_LRS
      zones:
      - "1"
  purpose: development
  region: westeurope
  secretBindingName: sap-skr-dev-cust-00002-kyma-integration
status:
  gardener:
    id: ""
    name: ""
    version: ""
  hibernated: false
  technicalID: ""
  uid: ""
```

**Comment by koala7659** [comment]
Env: Dev
PlanID: 7d55d31d-35ae-4438-bf13-6ffdfa107d9f
Plan name: **Trial**


```
metadata:
  annotations:
    compass.provisioner.kyma-project.io/operation-id: 2975fe37-c685-4e67-8d2e-0bf187717cec
    compass.provisioner.kyma-project.io/runtime-id: 5e85a763-ee3a-4802-b312-9a23a1aa3158
    kcp.provisioner.kyma-project.io/licence-type: TestDevelopmentAndDemo
    kcp.provisioner.kyma-project.io/operation-id: 2975fe37-c685-4e67-8d2e-0bf187717cec
    kcp.provisioner.kyma-project.io/runtime-id: 5e85a763-ee3a-4802-b312-9a23a1aa3158
  creationTimestamp: null
  labels:
    account: 461f6292-8085-41c8-af0c-e185f39b5e18
    subaccount: pg-test-su3
  name: c-872f7bf
  namespace: garden-kyma-dev
spec:
  cloudProfileName: aws
  dns:
    domain: c-872f7bf.dev.kyma.ondemand.com
    providers:
    - domains:
        include:
        - c-872f7bf.dev.kyma.ondemand.com
      primary: true
      secretName: aws-route53-secret-dev
      type: aws-route53
  extensions:
  - providerConfig:
      apiVersion: service.dns.extensions.gardener.cloud/v1alpha1
      dnsProviderReplication:
        enabled: true
      kind: DNSConfig
    type: shoot-dns-service
  - providerConfig:
      apiVersion: service.cert.extensions.gardener.cloud/v1alpha1
      kind: CertConfig
      shootIssuers:
        enabled: true
    type: shoot-cert-service
  - disabled: false
    type: shoot-networking-filter
  kubernetes:
    enableStaticTokenKubeconfig: false
    kubeAPIServer:
      auditConfig:
        auditPolicy:
          configMapRef:
            name: audit-policy
      oidcConfig:
        clientID: 9bd05ed7-a930-44e6-8c79-e6defeb7dec9
        groupsClaim: groups
        issuerURL: https://kymatest.accounts400.ondemand.com
        signingAlgs:
        - RS256
        usernameClaim: sub
        usernamePrefix: '-'
    version: "1.27"
  maintenance:
    autoUpdate:
      kubernetesVersion: true
      machineImageVersion: false
  networking:
    nodes: 10.250.0.0/22
    type: calico
  provider:
    controlPlaneConfig:
      apiVersion: aws.provider.extensions.gardener.cloud/v1alpha1
      kind: ControlPlaneConfig
    infrastructureConfig:
      apiVersion: aws.provider.extensions.gardener.cloud/v1alpha1
      kind: InfrastructureConfig
      networks:
        vpc:
          cidr: 10.250.0.0/22
        zones:
        - internal: 10.250.0.192/26
          name: eu-west-1a
          public: 10.250.0.128/26
          workers: 10.250.0.0/25
    type: aws
    workers:
    - machine:
        image:
          name: gardenlinux
          version: 1312.3.0
        type: m5.xlarge
      maxSurge: 1
      maxUnavailable: 0
      maximum: 1
      minimum: 1
      name: cpu-worker-0
      volume:
        size: 50Gi
        type: gp2
      zones:
      - eu-west-1a
  purpose: evaluation
  region: eu-west-1
  secretBindingName: aws-skr-dev-trial-00001
status:
  gardener:
    id: ""
    name: ""
    version: ""
  hibernated: false
  technicalID: ""
  uid: ""

```

**Review by m00g3n — APPROVED** [review]
LGTM

**Pull request merged**
