### PR TITLE
Allow configuring external compass URLs

### PR DESCRIPTION
**Pull request by ebensom**
**Description**

Changes proposed in this pull request:

- Eliminate compass URLs which hard-code the use of the cluster domain name
- Introduce chart variable for external compass gateway domain name

### CODE REVIEW

**Review by piotrmiskiewicz — DISMISSED** [review]

**Review by piotrmiskiewicz — APPROVED** [review]

**Review by rafalpotempa — APPROVED** [review]
Looks fine

**Review by franpog859 — COMMENTED** [review]
Let's maybe wait for the `pre-master-control-plane-gke-provisioner-integration` job to see if it works fine

**Comment by rafalpotempa** [comment]
You may need also approval from a Goat :)

**Review by colunira — APPROVED** [review]
/meow

**Pull request merged**
