### PR TITLE
Move image definitions to subcharts

### PR DESCRIPTION
**Pull request by piotrmiskiewicz**
**Description**

Changes proposed in this pull request:
- the docker images should not be defined in the main values.yaml

Reasons:
 - less spams from Github where someone creates a PR

### CODE REVIEW

**Review by franpog859 — DISMISSED** [review]

**Review by pbochynski — APPROVED** [review]
Even KCP is now modular! Thanks Piotr!

**Review by tobiscr — DISMISSED** [review]

**Review by franpog859 — APPROVED** [review]

**Review by PK85 — APPROVED** [review]

**Review by tobiscr — APPROVED** [review]

**Comment by piotrmiskiewicz** [comment]
https://github.com/kyma-project/control-plane/pull/2218

**Review by marcobebway — APPROVED** [review]

**Pull request merged**
