### PR TITLE
Support Shoot HA in provisioner

### PR DESCRIPTION
**Pull request by ebensom**
**Description**

Changes proposed in this pull request:

- Add support for configuring Shoot control plane failure tolerance level based on provision runtime input
- Remove configuring worker zones during shoot upgrade (as later migration will be implemented outside provisioner)

Shoot control plane failure tolerance is not an updateable input for provisioner (migration will be implemented outside of provisioner). Cluster operator shall support updating the control plane HA attribute though.

**Related issue(s)**

### CODE REVIEW

**Comment by ebensom** [comment]
go test works locally:

```
i349725@W-GZSM573:~/go/src/github.com/kyma-project/control-plane/components/provisioner$ go test ./... -timeout 15m
?       github.com/kyma-project/control-plane/components/provisioner/cmd        [no test files]
ok      github.com/kyma-project/control-plane/components/provisioner/internal/api       452.271s
?       github.com/kyma-project/control-plane/components/provisioner/internal/api/fake/seeds    [no test files]
?       github.com/kyma-project/control-plane/components/provisioner/internal/api/fake/shoots   [no test files]
?       github.com/kyma-project/control-plane/components/provisioner/internal/api/middlewares   [no test files]
?       github.com/kyma-project/control-plane/components/provisioner/internal/api/mocks [no test files]
ok      github.com/kyma-project/control-plane/components/provisioner/internal/apperrors (cached)
ok      github.com/kyma-project/control-plane/components/provisioner/internal/director  (cached)
?       github.com/kyma-project/control-plane/components/provisioner/internal/director/mocks    [no test files]
ok      github.com/kyma-project/control-plane/components/provisioner/internal/gardener  (cached)
?       github.com/kyma-project/control-plane/components/provisioner/internal/gardener/mocks    [no test files]
?       github.com/kyma-project/control-plane/components/provisioner/internal/graphql   [no test files]
?       github.com/kyma-project/control-plane/components/provisioner/internal/graphql/mocks     [no test files]
ok      github.com/kyma-project/control-plane/components/provisioner/internal/healthz   (cached)
ok      github.com/kyma-project/control-plane/components/provisioner/internal/installation      (cached)
?       github.com/kyma-project/control-plane/components/provisioner/internal/installation/mocks        [no test files]
ok      github.com/kyma-project/control-plane/components/provisioner/internal/installation/release      (cached)
?       github.com/kyma-project/control-plane/components/provisioner/internal/installation/release/mocks        [no test files]
ok      github.com/kyma-project/control-plane/components/provisioner/internal/metrics   (cached)
?       github.com/kyma-project/control-plane/components/provisioner/internal/metrics/mocks     [no test files]
ok      github.com/kyma-project/control-plane/components/provisioner/internal/model     (cached)
?       github.com/kyma-project/control-plane/components/provisioner/internal/model/infrastructure/aws  [no test files]
?       github.com/kyma-project/control-plane/components/provisioner/internal/model/infrastructure/azure        [no test files]
?       github.com/kyma-project/control-plane/components/provisioner/internal/model/infrastructure/gcp  [no test files]
?       github.com/kyma-project/control-plane/components/provisioner/internal/model/infrastructure/openstack    [no test files]
ok      github.com/kyma-project/control-plane/components/provisioner/internal/oauth     (cached)
?       github.com/kyma-project/control-plane/components/provisioner/internal/oauth/mocks       [no test files]
ok      github.com/kyma-project/control-plane/components/provisioner/internal/operations        (cached)
?       github.com/kyma-project/control-plane/components/provisioner/internal/operations/failure        [no test files]
?       github.com/kyma-project/control-plane/components/provisioner/internal/operations/mocks  [no test files]
?       github.com/kyma-project/control-plane/components/provisioner/internal/operations/queue  [no test files]
ok      github.com/kyma-project/control-plane/components/provisioner/internal/operations/stages/deprovisioning  (cached)
?       github.com/kyma-project/control-plane/components/provisioner/internal/operations/stages/deprovisioning/mocks    [no test files]
ok      github.com/kyma-project/control-plane/components/provisioner/internal/operations/stages/hibernation     (cached)
?       github.com/kyma-project/control-plane/components/provisioner/internal/operations/stages/hibernation/mocks       [no test files]
ok      github.com/kyma-project/control-plane/components/provisioner/internal/operations/stages/provisioning    (cached)
?       github.com/kyma-project/control-plane/components/provisioner/internal/operations/stages/provisioning/mocks      [no test files]
ok      github.com/kyma-project/control-plane/components/provisioner/internal/operations/stages/shootupgrade    (cached)
ok      github.com/kyma-project/control-plane/components/provisioner/internal/operations/stages/upgrade (cached)
ok      github.com/kyma-project/control-plane/components/provisioner/internal/persistence/database      (cached)
ok      github.com/kyma-project/control-plane/components/provisioner/internal/persistence/dberrors      (cached)
?       github.com/kyma-project/control-plane/components/provisioner/internal/persistence/testutils     [no test files]
ok      github.com/kyma-project/control-plane/components/provisioner/internal/provider-config-migrator  (cached)
ok      github.com/kyma-project/control-plane/components/provisioner/internal/provisioning      (cached)
?       github.com/kyma-project/control-plane/components/provisioner/internal/provisioning/mocks        [no test files]
ok      github.com/kyma-project/control-plane/components/provisioner/internal/provisioning/persistence/dbsession        (cached)
?       github.com/kyma-project/control-plane/components/provisioner/internal/provisioning/persistence/dbsession/mocks  [no test files]
ok      github.com/kyma-project/control-plane/components/provisioner/internal/runtime   (cached)
?       github.com/kyma-project/control-plane/components/provisioner/internal/runtime/mocks     [no test files]
ok      github.com/kyma-project/control-plane/components/provisioner/internal/util      (cached)
?       github.com/kyma-project/control-plane/components/provisioner/internal/util/k8s  [no test files]
?       github.com/kyma-project/control-plane/components/provisioner/internal/util/k8s/mocks    [no test files]
?       github.com/kyma-project/control-plane/components/provisioner/internal/util/testkit      [no test files]
?       github.com/kyma-project/control-plane/components/provisioner/internal/uuid      [no test files]
?       github.com/kyma-project/control-plane/components/provisioner/internal/uuid/mocks        [no test files]
ok      github.com/kyma-project/control-plane/components/provisioner/pkg/gqlschema      (cached)
?       github.com/kyma-project/control-plane/components/provisioner/pkg/scalar [no test files]
ok      github.com/kyma-project/control-plane/components/provisioner/third_party/machinebox/graphql     (cached)
i349725@W-GZSM573:~/go/src/github.com/kyma-project/control-plane/components/provisioner$ 
```

**Review by franpog859 — COMMENTED** [review]
The code looks fine. Proceeding to the manual tests

**Review by franpog859 — APPROVED** [review]
LGTM

**Review by lumi017 — APPROVED** [review]

**Pull request merged**
