### PR TITLE
Added configurable timeout for upgrade triggering

### PR DESCRIPTION
**Pull request by akgalwas**
**Description**

Changes proposed in this pull request:

- upgrade.triggeringTimeout property sets timeout for starting upgrade operation (default is 20 minutes)

### CODE REVIEW

**Review by koala7659 — APPROVED** [review]
lgtm

**Review by franpog859 — APPROVED** [review]
I provisioned the runtime, upgraded it successfully, changed the env value to `"1ms"`, upgraded again and it failed correctly. Looks good to me

**Review by franpog859 — APPROVED** [review]
still LGTM

**Pull request merged**
