### PR TITLE
Control Order

### PR DESCRIPTION
**Pull request by ralikio**
**Description**

Changes proposed in this pull request:

- Rewriting create to update `_controlsOrder`.

**Related issue(s)**

https://github.com/kyma-project/control-plane/issues/1273

### CODE REVIEW

**Review by PK85 — COMMENTED** [review]
components/kyma-environment-broker/internal/broker/testdata/update-free-azure-schema-additional-params.json

Check all testdata json files if we need to update those empty controls in update section.

**Comment by ralikio** [comment]
> components/kyma-environment-broker/internal/broker/testdata/update-free-azure-schema-additional-params.json
> 
> Check all testdata json files if we need to update those empty controls in update section.

**Comment by ralikio** [comment]
> components/kyma-environment-broker/internal/broker/testdata/update-free-azure-schema-additional-params.json
> 
> Check all testdata json files if we need to update those empty controls in update section.

It looks like testdata is used only in plan_test.go. The logic in this PR is outside of plan.go therefore we do not need to change anything in that files.

**Review by szwedm — APPROVED** [review]
/lgtm

**Pull request merged**
