### PR TITLE
Remove sc-migration code

### PR DESCRIPTION
**Pull request by wozniakjan**
**Description**

After the service catalog migration is finished, it's desired to remove the code responsible for enabling sc-migration component and simplify the code flow in KEB.

This depends on https://github.com/kyma-project/kyma/pull/13675

**Related issue(s)**

closes: https://github.com/kyma-project/control-plane/issues/1098

### CODE REVIEW

**Review by wozniakjan — COMMENTED** [review]
providing commentary for reviewers

**Comment by wozniakjan** [comment]
/hold
until management-plane config is merged too

**Comment by wozniakjan** [comment]
/unhold
management-plane config changes merged

**Comment by tillknuesting** [comment]
I think it's good, but I would like to get an additional review from @szwedm or @piotrmiskiewicz as this PR is not urgent to merge.

**Review by piotrmiskiewicz — APPROVED** [review]

**Pull request merged**
