### PR TITLE
remove cluster-essentials as a component reconciler

### PR DESCRIPTION
**Pull request by ruanxin**
**Description**

Changes proposed in this pull request:

Follow up cleanup due to https://github.com/kyma-incubator/reconciler/pull/1286

**Related issue(s)**
https://github.com/kyma-project/kyma/issues/16656

### CODE REVIEW

**Review by wozniakjan — APPROVED** [review]
thanks for the followup!

**Comment by ruanxin** [comment]
Hi @wozniakjan, 

can you confirm if the `cluster-essentials-reconciler` can be completely removed without affect KCP? 

Currently the KCP configured in [management-plane-config](https://github.tools.sap/kyma/management-plane-config/blob/master/resources/control-plane/dev/values.yaml#L57) still have `cluster-essentials-reconciler` enabled, but because your [PR](https://github.com/kyma-incubator/reconciler/pull/1286) has been merged, for next release, this component reconciler will end up into crash-loop. This already affect our control-plane test pipeline, check here: https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pre-main-control-plane-reconciler-e2e

If you confirmed it's safe to removed, then I'll create another followup ticket to cleanup management-plane-config repo, otherwise this can be a kyma release blocker issue.

**Comment by wozniakjan** [comment]
> can you confirm if the `cluster-essentials-reconciler` can be completely removed without affect KCP?

I can confirm it's desired to remove `PodPreset`, these are part of `cluster-essentials` kyma component that for now should stay but @PK85 informed me that @strekm is looking forward to later remove that too. https://github.com/kyma-project/kyma/issues/16656 was failing reconciler tests because some specifically had hardcoded checks for `PodPreset` related resources.

> Currently the KCP configured in management-plane-config still have cluster-essentials-reconciler enabled, but because your PR has been merged, for next release, this component reconciler will end up into crash-loop. 

Goal of https://github.com/kyma-incubator/reconciler/pull/1286 was to not have a custom `cluster-essentials` reconciler at all and use the base helm chart reconciler as the remaining part of `cluster-essentials` in kyma [a simple helm chart](https://github.com/kyma-project/kyma/tree/main/resources/cluster-essentials) without requirements on having own reconciler.

**Comment by ruanxin** [comment]
@wozniakjan, if as you said, the cluster-essentials component still needs to be removed later, then your [PR](https://github.com/kyma-incubator/reconciler/pull/1286) should be reverted, as I said, the `cluster-essentials-reconciler` with current reconciler code will end up into `CrashLoopBackOff` because there will be no service instance running in the pod.
The code remove should be done after this component deployment configuration get removed.
I'll close this PR, since cluster-essentials component can't be cleanup now.

You can have a look at some [failing pipeline](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pre-main-control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener) report.

https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_control-plane/2441/pre-main-control-plane-reconciler-e2e/1621131444241829888/build-log.txt


```
2023-02-02 09:30:36 UTC [INFO] PID:12 --- [/home/prow/go/src/github.com/kyma-project/test-infra/prow/scripts/cluster-integration/helpers/reconciler.sh] reconciler::wait_until_is_ready:115 NAME                                            READY   STATUS             RESTARTS      AGE
base-reconciler-694474d644-v6lpz                1/1     Running            0             21m
cleaner-reconciler-7f859bbb59-b5dhl             1/1     Running            0             21m
cluster-essentials-reconciler-99df988dc-jw8zx   0/1     CrashLoopBackOff   9 (34s ago)   21m

```

**Comment by wozniakjan** [comment]
```
2023-02-02 09:30:36 UTC [INFO] PID:12 --- [/home/prow/go/src/github.com/kyma-project/test-infra/prow/scripts/cluster-integration/helpers/reconciler.sh] reconciler::wait_until_is_ready:115 NAME                                            READY   STATUS             RESTARTS      AGE
base-reconciler-694474d644-v6lpz                1/1     Running            0             21m
cleaner-reconciler-7f859bbb59-b5dhl             1/1     Running            0             21m
cluster-essentials-reconciler-99df988dc-jw8zx   0/1     CrashLoopBackOff   9 (34s ago)   21m
```
lets figure out the residual places that start `cluster-essentials-reconciler`, the desired state is to not have it started and running by anything and instead, `cluster-essentials` component should be reconciled by base helm reconciler.

**Comment by wozniakjan** [comment]
meanwhile @ruanxin, https://github.com/kyma-incubator/reconciler/pull/1290 registers trivial `cluster-essentials` reconciler until we figure out how to fully remove it.

**Review by franpog859 — COMMENTED** [review]
@ruanxin , please, bump the Provisioner's image to `PR-2454` after the changes. Apart of that it looks good to me

**Review by koala7659 — APPROVED** [review]
LGTM

**Comment by koala7659** [comment]
@ruanxin Can you bump the Provisioner's image in `resources/kcp/charts/provisioner/values.yaml` file, please? Thanks!

**Pull request closed without merging**
