### PR TITLE
Adds ip ranges fields to provisioner

### PR DESCRIPTION
**Pull request by Disper**
**Description**

Changes proposed in this pull request:

- adds ip ranges fields to provisioner
- ...
- ...

**Related issue(s)**

#2946

### CODE REVIEW

**Review by m00g3n — APPROVED** [review]
LGTM

**Comment by Disper** [comment]
I've changed the title to include `do-not-merge/work-in-progress` label as during team meeting @koala7659 raised a concern regarding database migration.

**Review by koala7659 — CHANGES_REQUESTED** [review]
The implemented functionality does not seem to work. Gardener is not able to create a cluster with provided custom configuration for CNI networking plugin. This requires further investigation. Maybe such functionality is not supported at all by the Gardener, or maybe used values should be different? 

image

I can also noticed that values from ProvisionRuntime mutation were passed into shootTemplate as slightly modified. Could they be were changed by Gardener during runtime creation? We need to investigate.

Mutation config

```
                workerCidr: "10.250.0.0/19",
                podsCidr: "10.64.0.0/11",
                servicesCidr: "10.243.0.0/16"  
``` 

Created shoot template: 

```
  networking:
    type: calico
    providerConfig:
      overlay:
        enabled: false
    pods: 10.64.0.0/11
    nodes: 10.250.0.0/16
    services: 10.243.0.0/16
```

I think also we should return values for new fields when they are not provided by the user and are  assigned by the Gardener as we do for seed. Here is an example of current result of the query in case where values are not provided

```
                     "seed": "az-ha-eu1",
                    "workerCidr": "10.250.0.1/19",
                    "podsCidr": null,
                    "servicesCidr": null,
```
All we need to do is to store them in the database just after the moment when the cluster was successfully created. 
You can find the relevant example for seed in the [proceedToInstallation function](https://github.com/kyma-project/control-plane/blob/main/components/provisioner/internal/operations/stages/provisioning/wait_for_cluster_creation.go#L91C1-L114C9) in the Provisioning process.

**Comment by Disper** [comment]
Sharing some experiments that aim to narrow down the issue 
image

**Comment by Disper** [comment]
@koala7659 
> I can also noticed that values from ProvisionRuntime mutation were passed into shootTemplate as slightly modified. Could they be were changed by Gardener during runtime creation? We need to investigate.

I hope I've understood you correctly. Pods/nodes/services are how the gardener call those fields. For some unknown reason, in the past, we've named what represent`nodes` field on the provisioned side as `workedCidr`. Gardener is not changing those field, but rather we're assigning the values to [them here](https://github.com/kyma-project/control-plane/pull/2968/files#diff-503774e2175c9715d5639e33b7b8cd1a66097f93490cd49b6ed4d4ea9e5c1775R195-R198).

> https://github.com/kyma-project/control-plane/pull/2968/files#diff-503774e2175c9715d5639e33b7b8cd1a66097f93490cd49b6ed4d4ea9e5c1775R195-R198
Thanks! I'll look into that.

**Comment by Disper** [comment]
What's left as of now:
- [ ] Fix returning values of new field when they are not provided by the user
- [ ] extend components/provisioner/internal/api/resolver_integration_test.go

**Review by koala7659 — APPROVED** [review]
LGTM

**Review by grego952 — APPROVED** [review]

**Pull request merged**
