### PR TITLE
KEB istio config for events api

### PR DESCRIPTION
**Pull request by wozniakjan**
**Description**

I missed istio `VirtualService` config in https://github.com/kyma-project/control-plane/pull/2114 which resulted in all requests for events by KCP https://github.com/kyma-project/control-plane/pull/2126 were rejected with 404 by envoy proxy.

**Related issue(s)**

### CODE REVIEW

**Comment by wozniakjan** [comment]
`pre-main-control-plane-gke-integration` keept failing with:
```
control plane installation error, description: install component kcp
Installation errors until timeout:
----------

kcp:
  Helm installation of release "kcp" failed: timed out waiting for the condition
Deleting release before retrying.
```

checking why. It's also pretty weird `pre-main-control-plane-integration` passed just fine...

**Comment by wozniakjan** [comment]
without https://github.com/kyma-project/control-plane/pull/2165/commits/9c1edf3188357983c5207503bec6b81987a8700a [it passed](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_control-plane/2165/pre-main-control-plane-gke-integration/1582708970856910848)

**Review by jaroslaw-pieszka — APPROVED** [review]

**Pull request merged**
