### PR TITLE
Enable debug logs for KCP CLI

### PR DESCRIPTION
**Pull request by khlifi411**
**Description**

Changes proposed in this pull request:

- Changed reconciler OAPI version
- Generated MR REST client
- Implemented `reconciliations operation debug` command
- Implemented `reconciliations debug` command

**Related issue(s)**
https://github.com/kyma-incubator/reconciler/issues/949

### CODE REVIEW

**Review by adityabhatia — APPROVED** [review]
lgtm 🌕  🚀

**Review by ralikio — APPROVED** [review]
PR does not touch our code.

**Pull request merged**
