### PR TITLE
add e2e test for aws

### PR DESCRIPTION
**Pull request by life0215**
**Description**

add e2e-aws TestDefinition
- ...
- ...
- ...

**Related issue(s)**

### CODE REVIEW

**Comment by tobiscr** [comment]
@life0215 : If you need support on getting this Spinnaker pipelie flying, please contact @ksputo . He worked also on this topic.

**Comment by life0215** [comment]
Hi, @ksputo  and Team
Can you help review this PR? Did some test on dev landscape, looks OK.

**Review by jasiu001 — APPROVED** [review]

**Pull request merged**
