### PR TITLE
Fix KEB starting

### PR DESCRIPTION
**Pull request by polskikiel**
**Description**

Changes proposed in this pull request:

- Fixed KEB starting

**Related issue(s)**

### CODE REVIEW

**Comment by mszostok** [comment]
I don't understand how this will solve issue described here: https://github.com/kyma-incubator/compass/issues/1341 
Let's discuss that f2f 🙂

**Comment by ebensom** [comment]
I'm also thinking to increase the liveness probe `initialDelaySeconds` (maybe to 30s?) because the container restarts could be initiated by kubelet because the container is not responding to the liveness probe according to the configured settings. After 2 restarts, the istio-proxy sidecar is ready to proxy traffic so the liveness probe can reach KEB's healthz handler which responds back with 200 OK (edited) 

 I have no knowledge what issue will it solve to wait for the K8S client mapper to be ready

**Pull request merged**
