### PR TITLE
Errors categorization - changes for provisioner and schema-migrator

### PR DESCRIPTION
**Pull request by vvxxvvxx**
**Description**

Changes proposed in this pull request:

- This PR is to separate the code changes of provisioner and schema-migrator from the PR-1369 https://github.com/kyma-project/control-plane/pull/1369
- Make the errors categorized as error component(category), error reason and error message.
- Add the categorization error info into gcli.ExtendedError and operation LastError

The **tests** performed are summarized [here](https://github.tools.sap/kyma/backlog/issues/1933#issuecomment-755314)

**Related issue(s)**

### CODE REVIEW

**Comment by vvxxvvxx** [comment]
/test 
pre-main-control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener

**Review by Maladie — DISMISSED** [review]

**Comment by vvxxvvxx** [comment]
in PR #1408 , the executor process break when the err returns `ErrKubeconfigNil`, https://github.com/kyma-project/control-plane/blob/81b34edb04688d266d633a06296b8c9e6f1d025d/components/provisioner/internal/operations/executor.go#L122
left the comment to know why https://github.com/kyma-project/control-plane/pull/1408#discussion_r825551497 .

And in `pre-control-plane-components-provisioner` test job, for the test `testProvisionRuntime` of `TestProvisioning_ProvisionRuntimeWithDatabase`, is returning err `the cluster kubeconfig is nil` expected in step`CreatingBindingsForOperators`? 
```
[0558] | time="2022-03-11T04:58:21Z" level=warning msg="Warning, the cluster kubeconfig is nil" Component=Executor OperationId=d2033455-f2c1-4105-81ba-b5cf7ec2743d OperationType=PROVISION RuntimeId=1100bb59-9c40-4ebb-b846-7477c4dc5bb8 ShootName=c-572f1cc Stage=CreatingBindingsForOperators component="operations/executor.go:122:operations.(*Executor).process"
```

**Review by Maladie — APPROVED** [review]

**Pull request merged**
