### PR TITLE
Refactor provisioner tests env

### PR DESCRIPTION
**Pull request by VOID404**
**Description**

Changes proposed in this pull request:

- Remove multiple layers of docker from tests
- Modify workflow to use `actions/setup-go@v5`
- Bump buildpack
- Remove special test-env handling from database code

**Related issue(s)**

#3287

### CODE REVIEW

**Comment by VOID404** [comment]
E2e tests pass, with fixed CIDRs
image

**Review by grego952 — APPROVED** [review]

**Pull request merged**
