### PR TITLE
change avs monitor naming convention on create

### PR DESCRIPTION
**Pull request by Balazs23**
**Description**

Changes proposed in this pull request:

- replace `subAccountID` with `instanceID` for AVS EV name
- change description format to `json` for further possible integrations and include `instanceID`

**Related issue(s)**

https://github.tools.sap/kyma/backlog/issues/1159

### CODE REVIEW

**Review by jasiu001 — APPROVED** [review]

**Comment by Balazs23** [comment]
`
ERROR: (gcloud.dns.record-sets.transaction.execute) HTTPError 400: Invalid value for 'entity.change.additions[1].rrdata[0]': '2021/06/30 13:08:46 UTC [INFO] Reserve IP Address for gkekcpint-pr-804-y2js008enc
`

/test pre-main-control-plane-gke-integration

**Comment by Balazs23** [comment]
finally, @jasiu001 could you please give me a `lgtm` label again? thank you

**Review by crabtree — APPROVED** [review]

**Pull request merged**
