### PR TITLE
Add configmaps for new migrations

### PR DESCRIPTION
**Pull request by MarekMichali**
**Description**

Changing the schema for any control-plane components should not require bump of the schema migrator.
The migrator is able to use files defined in other locations than in the docker image.

The idea is to mount all new migrations using configmaps in the locations where the migrator is able to find them.

Changes proposed in this pull request:

- Add configmaps for new migrations.
- Mount configmaps.
- Adjust bash scripts.
- Update docs.

**Related issue(s)**

### CODE REVIEW

**Comment by franpog859** [comment]
Is it ready for review? Why is it labeled with the `do-not-merge/hold` label?

**Comment by MarekMichali** [comment]
> 

Yes it's ready for review. I want to make sure that a TW will review the documentation after developers review.

**Review by mvshao — COMMENTED** [review]
Changes regarding Provisioner look good to me. I will give approval if the conflict is resolved.

**Review by ralikio — APPROVED** [review]

**Review by mvshao — DISMISSED** [review]

**Review by IwonaLanger — APPROVED** [review]

**Review by ralikio — APPROVED** [review]

**Review by mvshao — DISMISSED** [review]

**Review by franpog859 — DISMISSED** [review]
Previously approved by @mvshao

**Review by ralikio — APPROVED** [review]

**Review by mvshao — APPROVED** [review]

**Review by IwonaLanger — APPROVED** [review]

**Pull request merged**
