### PR TITLE
Request Email and OpenID scopes in oidc-login

### PR DESCRIPTION
**Pull request by kwiatekus**
**Description**

Changes proposed in this pull request:

- Request extra scopes `email` and `openid` to support custom oidc configurations where email is targeted as username

**Related issue(s)**
Fixes https://github.com/kyma-project/control-plane/issues/1062

### CODE REVIEW

**Review by wozniakjan — APPROVED** [review]
/lgtm

**Review by ksputo — DISMISSED** [review]

**Comment by ksputo** [comment]
Please bump KEB image here:
https://github.com/kyma-project/control-plane/blob/main/resources/kcp/values.yaml#L21

**Comment by kwiatekus** [comment]
> Please bump KEB image here: https://github.com/kyma-project/control-plane/blob/main/resources/kcp/values.yaml#L21

I actually bumped all the products of the presubmit jobs related to my PR...

**Review by ksputo — APPROVED** [review]

**Review by strekm — APPROVED** [review]
/meow

**Pull request merged**
