### PR TITLE
Remove rma resources

### PR DESCRIPTION
**Pull request by vvxxvvxx**
**Description**

Changes proposed in this pull request:

- As we have be using RMO to replace the legacy rma-reconciler, so remove the rma resources from KEB.

**Related issue(s)**

### CODE REVIEW

**Comment by Tomasz-Smelcerz-SAP** [comment]
/test pre-main-control-plane-reconciler-e2e-latest-release
--



<p dir="auto"><a href="https://status.build.kyma-project.io/pr-history?org=kyma-project&amp;repo=control-plane&amp;pr=3091" rel="nofollow"></a></p>

**Review by akgalwas — APPROVED** [review]

**Review by ebensom — DISMISSED** [review]

**Review by ebensom — APPROVED** [review]

**Review by lindnerby — APPROVED** [review]

**Review by MarekMichali — APPROVED** [review]

**Review by marcobebway — APPROVED** [review]

**Review by tobiscr — APPROVED** [review]

**Pull request merged**
