### PR TITLE
use plan_id as metric label instead of using plan_name in metric name

### PR DESCRIPTION
**Pull request by life0215**
…

**Description**

Changes proposed in this pull request:

- consolidate plan_id usage in metrics, propose to use plan_id as metric label instead of using plan_name as part of metric name

**Related issue(s)**

### CODE REVIEW

**Review by ebensom — APPROVED** [review]

**Comment by klaudiagrz** [comment]
@life0215 Make sure to keep both plan_id and plan_name for not breaking compatibility

**Comment by life0215** [comment]
> @life0215 Make sure to keep both plan_id and plan_name for not breaking compatibility


We have only one grafana [dashboard](https://github.com/kyma-project/control-plane/blob/main/resources/kcp/charts/kyma-environment-broker/files/dashboard.json#L915) which consumes these metrics and expecting KEB metrics to have consolidated labels and metric naming( i.e. changes in this PR).
So we are not expecting breaking compatibility. 

Unfortunately keeping the plan_name in metric names will make this PR meaningless. We still need to deal with two sets of variables plan_name, plan_id. which is time consuming and hard to maintain.

Do we have any other service which are integrated with these metrics ?

**Comment by szwedm** [comment]
Looks good, I just wonder if image should be bumped?

**Comment by szwedm** [comment]
One more question, was the dashboard adjusted to incorporate these changes ?

**Review by szwedm — APPROVED** [review]

**Comment by life0215** [comment]
> @life0215 one more question, was the dashboard adjusted to incorporate these changes ?

Thanks, am working on the adjustment.

**Pull request merged**
