### PR TITLE
Add name parameter to GardenerConfigInput

### PR DESCRIPTION
**Pull request by Maladie**
**Description**

Changes proposed in this pull request:

- ShootCR name is no longer generated in Provisioner, it is now moved to parameter in GardenerConfigInput

**Related issue(s)**

#309

### CODE REVIEW

**Review by majakurcius — APPROVED** [review]

**Review by franpog859 — APPROVED** [review]
Please, be sure that the integration test from the `pre-master-control-plane-gke-provisioner-integration` job finished successfully

**Review by majakurcius — APPROVED** [review]

**Pull request merged**
