### PR TITLE
Remove unused function from HAP

### PR DESCRIPTION
**Pull request by Maladie**
**Description**

Changes proposed in this pull request:

- remove [getting Secret operation from the Hyperscaler Account Provider](https://github.com/kyma-project/control-plane/blob/main/components/kyma-environment-broker/common/hyperscaler/account_provider.go#L114-L127) as [its data is no longer needed](https://github.com/kyma-project/control-plane/blob/main/components/kyma-environment-broker/internal/process/provisioning/resolve_creds.go#L105)

**Related issue(s)**

See [the issue here](https://github.tools.sap/kyma/backlog/issues/1395)

### CODE REVIEW

**Review by rafalpotempa — APPROVED** [review]
Looks ok to me, but Gophers should also look into it.

**Review by wozniakjan — APPROVED** [review]
/lgtm

**Review by wozniakjan — APPROVED** [review]
/lgtm

**Review by crabtree — APPROVED** [review]

**Review by PK85 — APPROVED** [review]

**Pull request merged**
